name: Build and Publish .NET 8.0 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  OUTPUT_DIR: 'publish'

jobs:
  build:
    name: Build .NET 8.0 App
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      
    - name: Publish
      run: dotnet publish -c ${{ env.BUILD_CONFIGURATION }} -o ${{ github.workspace }}/${{ env.OUTPUT_DIR }} --no-build
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: ${{ github.workspace }}/${{ env.OUTPUT_DIR }}/**
        retention-days: 1