name: Build and Release Windows EXE

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Single EXE
      run: |
        dotnet publish -c Release -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeAllContentForSelfExtract=true `
          -o publish
        
        $exeName = (Get-ChildItem -Path "publish" -Filter "*.exe").Name
        echo "EXE_NAME=$exeName" >> $env:GITHUB_ENV

    - name: Prepare Release Assets
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}".Substring(1)        
        Copy-Item -Path "publish/${{ env.EXE_NAME }}" -Destination "${{ env.EXE_NAME }}"        
        Compress-Archive -Path "publish/*" -DestinationPath "LibertyActivator-$version.zip"
        echo "ZIP_NAME=LibertyActivator-$version.zip" >> $env:GITHUB_ENV

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ env.EXE_NAME }}
          ${{ env.ZIP_NAME }}