name: Build and Release Windows EXE

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Single EXE
      run: |
        dotnet publish -c Release -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeAllContentForSelfExtract=true `
          -p:EnableCompressionInSingleFile=true `
          -o publish

    - name: Create Release ZIP
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}".Substring(1)
        $exeName = (Get-ChildItem -Path "publish" -Filter "*.exe").Name
        Compress-Archive -Path "publish/$exeName" -DestinationPath "LibertyActivator-$version.zip"
        echo "ZIP_NAME=LibertyActivator-$version.zip" >> $env:GITHUB_ENV

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.ZIP_NAME }}