name: Build and Release Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Standalone EXE
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

    - name: Create Release ZIP
      shell: pwsh
      run: |
        $version = (Get-Item publish/*.exe).Basename
        Compress-Archive -Path publish/* -DestinationPath "LibertyActivator-$version.zip"

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: LibertyActivator-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}